services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SourceBroker\Imageopt\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Configuration/Configurator.php'
      - '../Classes/Service/OptimizeImageService.php'
      - '../Classes/Service/OptimizeImagesFalService.php'
      - '../Classes/Service/OptimizeImagesFolderService.php'

  SourceBroker\Imageopt\Command\OptimizeFolderImages:
    tags:
      - name: 'console.command'
        command: 'imageopt:optimizefolderimages'
        schedulable: true

  SourceBroker\Imageopt\Command\OptimizeFalProcessedImages:
    tags:
      - name: 'console.command'
        command: 'imageopt:optimizefalprocessedimages'
        schedulable: true

  SourceBroker\Imageopt\Command\ResetOptimizationFlagForFal:
    tags:
      - name: 'console.command'
        command: 'imageopt:resetoptimizationflagforfal'
        schedulable: false

  SourceBroker\Imageopt\Command\ResetOptimizationFlagForFolders:
    tags:
      - name: 'console.command'
        command: 'imageopt:resetoptimizationflagforfolders'
        schedulable: false
